remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Building an intelligent system to detect respiratory insufficiency
description: Page for the discipline MAC0499 - Capstone Project - from IME-USP.
